var path = require("path");
var webpack = require("webpack");
var TimestampWebpackPlugin = require("timestamp-webpack-plugin");

module.exports = {
    context: path.resolve("js"),
    entry: ["./app", "./utils"],
    output: {
        path: path.resolve("build/"),
        publicPath: "/public/assets/js",
        filename: "bundle.js"
    },
    watch: true,
    devServer: {
        contentBase: "public"
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
        new TimestampWebpackPlugin({
            path: __dirname,
            filename: "timestamp.json"
        }),
        new webpack.BannerPlugin("**********\nGenerated by Webpack\n**********\n")
    ],
    module: {
        rules: [
            {
                test: /\.es6$/,
                exclude: /node_modules/,
                loader: "babel-loader"
            }
        ]
    },
    resolve: {
        extensions: [".js", ".es6"]
    }
}